# Generated by Django 4.2.2 on 2023-06-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='page',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='price',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterModelTable(
            name='bookmodel',
            table='book',
        ),
    ]
