# Generated by Django 4.2.2 on 2023-06-27 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_bookmodel_page_bookmodel_price_alter_bookmodel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='authormodel',
            table=None,
        ),
    ]
